"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.get_reader_response_customer import \
    GetReaderResponseCustomer


class TestGetReaderResponseCustomer(unittest.TestCase):
    """GetReaderResponseCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetReaderResponseCustomer:
        """Test GetReaderResponseCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetReaderResponseCustomer`
        """
        model = GetReaderResponseCustomer()
        if include_optional:
            return GetReaderResponseCustomer(
                reader_id = '',
                first_name = '',
                last_name = '',
                email = '',
                access_scope = d361api.models.access_scope_customer_v2.AccessScopeCustomerV2(
                    access_level = null, 
                    categories = [
                        d361api.models.category_summary_customer_v2.CategorySummaryCustomerV2(
                            category_id = '', 
                            project_version_id = '', 
                            language_code = '', )
                        ], 
                    project_versions = [
                        ''
                        ], 
                    languages = [
                        d361api.models.language_summary_customer.LanguageSummaryCustomer(
                            project_version_id = '', 
                            language_code = '', )
                        ], ),
                associated_reader_groups = [
                    ''
                    ],
                is_invite_sso_user = True,
                last_login_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetReaderResponseCustomer(
        )
        """

    def testGetReaderResponseCustomer(self):
        """Test GetReaderResponseCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
