"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.form_editable_properties import FormEditableProperties


class TestFormEditableProperties(unittest.TestCase):
    """FormEditableProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FormEditableProperties:
        """Test FormEditableProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FormEditableProperties`
        """
        model = FormEditableProperties()
        if include_optional:
            return FormEditableProperties(
                element_name = '',
                element_type = 0,
                label = '',
                value = '',
                view_form_control = d361api.models.view_form_control.ViewFormControl(
                    property_key = '', 
                    is_children = 56, 
                    view_type = '', 
                    element_name = '', 
                    is_children_root = True, 
                    element_type = '', 
                    inverted_value = True, 
                    is_dirty = True, ),
                editable_properties = d361api.models.form_editable_properties.FormEditableProperties(
                    element_name = '', 
                    element_type = null, 
                    label = '', 
                    value = '', 
                    view_form_control = null, 
                    editable_properties = null, 
                    element_guid = '', 
                    children = [
                        d361api.models.form_editable_properties.FormEditableProperties(
                            element_name = '', 
                            element_type = null, 
                            label = '', 
                            value = '', 
                            view_form_control = null, 
                            editable_properties = null, 
                            element_guid = '', 
                            edit_component_style_properties = {
                                'key' : null
                                }, 
                            edit_component_properties = {
                                'key' : null
                                }, )
                        ], 
                    edit_component_style_properties = {
                        'key' : null
                        }, 
                    edit_component_properties = {
                        'key' : null
                        }, ),
                element_guid = '',
                children = [
                    d361api.models.form_editable_properties.FormEditableProperties(
                        element_name = '', 
                        element_type = null, 
                        label = '', 
                        value = '', 
                        view_form_control = null, 
                        editable_properties = null, 
                        element_guid = '', 
                        edit_component_style_properties = {
                            'key' : null
                            }, 
                        edit_component_properties = {
                            'key' : null
                            }, )
                    ],
                edit_component_style_properties = {
                    'key' : null
                    },
                edit_component_properties = {
                    'key' : null
                    }
            )
        else:
            return FormEditableProperties(
        )
        """

    def testFormEditableProperties(self):
        """Test FormEditableProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
