"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.ai_assistive_search import AIAssistiveSearch


class TestAIAssistiveSearch(unittest.TestCase):
    """AIAssistiveSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIAssistiveSearch:
        """Test AIAssistiveSearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIAssistiveSearch`
        """
        model = AIAssistiveSearch()
        if include_optional:
            return AIAssistiveSearch(
                prompt = '',
                result = '',
                reference_articles = [
                    d361api.models.vector_search_reference_articles.VectorSearchReferenceArticles(
                        id = '', 
                        citation_id = '', 
                        category_id = '', 
                        category_title = '', 
                        category_slug = '', 
                        version_name = '', 
                        version_slug = '', 
                        article_id = '', 
                        article_title = '', 
                        article_slug = '', 
                        version_display_name = '', 
                        language_code = '', 
                        data_source_type = null, 
                        external_source_link = '', 
                        external_source_name = '', 
                        external_source_id = '', )
                    ],
                limit_exceeded = True,
                analytics_id = '',
                remaining_credits = 56,
                extension_data = None,
                context = d361api.models.base_response_context.BaseResponseContext(
                    extension_data = null, 
                    caller_reference = '', ),
                success = True,
                errors = [
                    d361api.models.base_error.BaseError(
                        extension_data = null, 
                        stack_trace = '', 
                        description = '', 
                        error_code = '', 
                        custom_data = {
                            'key' : null
                            }, )
                    ],
                warnings = [
                    d361api.models.base_warning.BaseWarning(
                        extension_data = null, 
                        description = '', 
                        warning_code = '', )
                    ],
                information = [
                    d361api.models.base_information.BaseInformation(
                        extension_data = null, 
                        description = '', )
                    ],
                feature_explorer_status = d361api.models.feature_explorer_status.FeatureExplorerStatus(
                    feature_usage_score = 1.337, 
                    section = null, 
                    feature_id = '', 
                    feature_name = null, 
                    advanced_feature_user_role = null, 
                    feature_explorer_user_analytics = null, ),
                custom_page_element = d361api.models.ui_element.UIElement(
                    element_type = null, 
                    element_name = '', 
                    element_guid = '', 
                    display_name = '', 
                    view_styles = {
                        'key' : null
                        }, 
                    view_properties = {
                        'key' : null
                        }, 
                    editable_properties = [
                        d361api.models.form_editable_properties.FormEditableProperties(
                            element_name = '', 
                            element_type = null, 
                            label = '', 
                            value = '', 
                            view_form_control = null, 
                            element_guid = '', 
                            children = [
                                d361api.models.form_editable_properties.FormEditableProperties(
                                    element_name = '', 
                                    element_type = null, 
                                    label = '', 
                                    value = '', 
                                    view_form_control = null, 
                                    element_guid = '', 
                                    edit_component_style_properties = {
                                        'key' : null
                                        }, 
                                    edit_component_properties = {
                                        'key' : null
                                        }, )
                                ], 
                            edit_component_style_properties = {
                                'key' : null
                                }, 
                            edit_component_properties = {
                                'key' : null
                                }, )
                        ], 
                    children = [
                        d361api.models.ui_element.UIElement(
                            element_type = null, 
                            element_name = '', 
                            element_guid = '', 
                            display_name = '', )
                        ], )
            )
        else:
            return AIAssistiveSearch(
        )
        """

    def testAIAssistiveSearch(self):
        """Test AIAssistiveSearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
