"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.hit import Hit


class TestHit(unittest.TestCase):
    """Hit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Hit:
        """Test Hit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Hit`
        """
        model = Hit()
        if include_optional:
            return Hit(
                title = '',
                content = '',
                is_hidden = True,
                tags = [
                    ''
                    ],
                slug = '',
                version = 56,
                article_id = '',
                category_id = '',
                is_category_hidden = True,
                order = 56,
                is_draft = True,
                exclude = True,
                breadcrumb = '',
                is_category = True,
                attachment_ids = [
                    null
                    ],
                is_deleted = True,
                is_folder_type_category = True,
                updated_on_timestamp = 1.337,
                is_private = True,
                language_id = '',
                project_id = '',
                is_latest_version = True,
                contributors = [
                    ''
                    ],
                is_shared_article = 56,
                lang_code = '',
                category_unique_id = '',
                unique_id = '',
                deleted_by = '',
                deleted_at = '',
                is_git_hub_entity = True,
                original_article_id = '',
                object_id = '',
                snippet_result = d361api.models._snippetresult._Snippetresult(
                    content = null, ),
                highlight_result = d361api.models._highlightresult._Highlightresult(
                    title = null, )
            )
        else:
            return Hit(
        )
        """

    def testHit(self):
        """Test Hit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
