"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.content_role_info import ContentRoleInfo


class TestContentRoleInfo(unittest.TestCase):
    """ContentRoleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentRoleInfo:
        """Test ContentRoleInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentRoleInfo`
        """
        model = ContentRoleInfo()
        if include_optional:
            return ContentRoleInfo(
                version_access_info = d361api.models.version_access_info.VersionAccessInfo(
                    version_name = '', 
                    version_id = '', ),
                language_access_info = d361api.models.language_access_info.LanguageAccessInfo(
                    language_id = '', 
                    language_name = '', 
                    language_code = '', 
                    version_name = '', 
                    version_id = '', ),
                category_access_info = d361api.models.category_access_info.CategoryAccessInfo(
                    category_name = '', 
                    category_id = '', 
                    language_id = '', 
                    language_name = '', 
                    language_code = '', 
                    version_name = '', 
                    version_id = '', ),
                article_access_info = d361api.models.article_access_info.ArticleAccessInfo(
                    article_name = '', 
                    category_name = '', 
                    category_id = '', 
                    language_id = '', 
                    language_name = '', 
                    language_code = '', 
                    version_name = '', 
                    version_id = '', ),
                access_scope_level = 0,
                role_name = '',
                role_id = '',
                group_name = ''
            )
        else:
            return ContentRoleInfo(
        )
        """

    def testContentRoleInfo(self):
        """Test ContentRoleInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
