"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.role_summary_customer import RoleSummaryCustomer


class TestRoleSummaryCustomer(unittest.TestCase):
    """RoleSummaryCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoleSummaryCustomer:
        """Test RoleSummaryCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoleSummaryCustomer`
        """
        model = RoleSummaryCustomer()
        if include_optional:
            return RoleSummaryCustomer(
                role_id = '',
                role_name = ''
            )
        else:
            return RoleSummaryCustomer(
        )
        """

    def testRoleSummaryCustomer(self):
        """Test RoleSummaryCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
