"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.language_scope_customer import LanguageScopeCustomer


class TestLanguageScopeCustomer(unittest.TestCase):
    """LanguageScopeCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LanguageScopeCustomer:
        """Test LanguageScopeCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LanguageScopeCustomer`
        """
        model = LanguageScopeCustomer()
        if include_optional:
            return LanguageScopeCustomer(
                project_version_id = '0',
                language_code = '0'
            )
        else:
            return LanguageScopeCustomer(
                project_version_id = '0',
                language_code = '0',
        )
        """

    def testLanguageScopeCustomer(self):
        """Test LanguageScopeCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
