"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.edit_content_role_customer import EditContentRoleCustomer


class TestEditContentRoleCustomer(unittest.TestCase):
    """EditContentRoleCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditContentRoleCustomer:
        """Test EditContentRoleCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditContentRoleCustomer`
        """
        model = EditContentRoleCustomer()
        if include_optional:
            return EditContentRoleCustomer(
                content_permissions = [
                    d361api.models.content_permission_customer.ContentPermissionCustomer(
                        associated_content_role_id = '0', 
                        access_scope = null, )
                    ],
                is_invitation_id = True
            )
        else:
            return EditContentRoleCustomer(
                content_permissions = [
                    d361api.models.content_permission_customer.ContentPermissionCustomer(
                        associated_content_role_id = '0', 
                        access_scope = null, )
                    ],
        )
        """

    def testEditContentRoleCustomer(self):
        """Test EditContentRoleCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
