"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.readers_api import ReadersApi


class TestReadersApi(unittest.IsolatedAsyncioTestCase):
    """ReadersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ReadersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_v2_readers_get(self) -> None:
        """Test case for v2_readers_get

        Get all available readers from the project
        """
        pass

    async def test_v2_readers_groups_get(self) -> None:
        """Test case for v2_readers_groups_get

        Get all reader groups
        """
        pass

    async def test_v2_readers_groups_group_id_delete(self) -> None:
        """Test case for v2_readers_groups_group_id_delete

        Deletes a reader group
        """
        pass

    async def test_v2_readers_groups_group_id_get(self) -> None:
        """Test case for v2_readers_groups_group_id_get

        Get a reader group via group id
        """
        pass

    async def test_v2_readers_groups_group_id_put(self) -> None:
        """Test case for v2_readers_groups_group_id_put

        Updates a reader group
        """
        pass

    async def test_v2_readers_groups_post(self) -> None:
        """Test case for v2_readers_groups_post

        Add a new reader group
        """
        pass

    async def test_v2_readers_jwt_delete(self) -> None:
        """Test case for v2_readers_jwt_delete

        Deletes JWT readers from the project
        """
        pass

    async def test_v2_readers_post(self) -> None:
        """Test case for v2_readers_post

        Add a new reader
        """
        pass

    async def test_v2_readers_reader_id_delete(self) -> None:
        """Test case for v2_readers_reader_id_delete

        Deletes a reader from the project
        """
        pass

    async def test_v2_readers_reader_id_put(self) -> None:
        """Test case for v2_readers_reader_id_put

        Updates a reader
        """
        pass


if __name__ == '__main__':
    unittest.main()
