"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.media_file_and_tags_meta_data_customer import \
    MediaFileAndTagsMetaDataCustomer


class TestMediaFileAndTagsMetaDataCustomer(unittest.TestCase):
    """MediaFileAndTagsMetaDataCustomer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaFileAndTagsMetaDataCustomer:
        """Test MediaFileAndTagsMetaDataCustomer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaFileAndTagsMetaDataCustomer`
        """
        model = MediaFileAndTagsMetaDataCustomer()
        if include_optional:
            return MediaFileAndTagsMetaDataCustomer(
                id = '0',
                file_name = '',
                file_type = '',
                file_url = '',
                updated_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = '',
                size = '',
                height = '',
                width = '',
                parent_folder_id = '',
                title = '',
                alternative_text = '',
                tags = [
                    d361api.models.tags_meta_data_customer.TagsMetaDataCustomer(
                        id = '', 
                        tag_name = '', )
                    ],
                thumbnail_url = '',
                is_starred = True
            )
        else:
            return MediaFileAndTagsMetaDataCustomer(
                id = '0',
        )
        """

    def testMediaFileAndTagsMetaDataCustomer(self):
        """Test MediaFileAndTagsMetaDataCustomer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
