"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.project_versions_api import ProjectVersionsApi


class TestProjectVersionsApi(unittest.IsolatedAsyncioTestCase):
    """ProjectVersionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProjectVersionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_v2_project_versions_ask_eddy_post(self) -> None:
        """Test case for v2_project_versions_ask_eddy_post

        Perform AI assistive search within project version
        """
        pass

    async def test_v2_project_versions_get(self) -> None:
        """Test case for v2_project_versions_get

        Gets list of project versions
        """
        pass

    async def test_v2_project_versions_project_version_id_apireferences_get(self) -> None:
        """Test case for v2_project_versions_project_version_id_apireferences_get

        Gets list of api reference within project version
        """
        pass

    async def test_v2_project_versions_project_version_id_articles_get(self) -> None:
        """Test case for v2_project_versions_project_version_id_articles_get

        Gets list of articles within project version
        """
        pass

    async def test_v2_project_versions_project_version_id_categories_get(self) -> None:
        """Test case for v2_project_versions_project_version_id_categories_get

        Gets list of categories within project version
        """
        pass

    async def test_v2_project_versions_project_version_id_lang_code_get(self) -> None:
        """Test case for v2_project_versions_project_version_id_lang_code_get

        Searches for a phrase inside project version
        """
        pass


if __name__ == '__main__':
    unittest.main()
