# coding: utf-8

"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from d361api.d361api.public_apiai_feedback_request import PublicAPIAIFeedbackRequest

class TestPublicAPIAIFeedbackRequest(unittest.TestCase):
    """PublicAPIAIFeedbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicAPIAIFeedbackRequest:
        """Test PublicAPIAIFeedbackRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicAPIAIFeedbackRequest`
        """
        model = PublicAPIAIFeedbackRequest()
        if include_optional:
            return PublicAPIAIFeedbackRequest(
                entity_id = '',
                is_liked = True,
                comments = '',
                notify_me_about_changes = True,
                feedback_provider_email = '',
                additional_feedback_info = d361api.models.ai_additional_feedback_info.AIAdditionalFeedbackInfo(
                    need_more_information = True, 
                    difficult_to_understand = True, 
                    irrelevant_content = True, 
                    incorrect_source_reference = True, 
                    missing_information = True, 
                    dont_like_style = True, 
                    others = True, 
                    comments = True, ),
                feedback_sub_type = 0
            )
        else:
            return PublicAPIAIFeedbackRequest(
        )
        """

    def testPublicAPIAIFeedbackRequest(self):
        """Test PublicAPIAIFeedbackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
