"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

from d361api.d361api.language import Language


class TestLanguage(unittest.TestCase):
    """Language unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Language:
        """Test Language
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Language`
        """
        model = Language()
        if include_optional:
            return Language(
                id = '',
                name = '',
                code = '',
                set_as_default = True,
                hidden = True,
                enable_rtl = True,
                site_protection_level = 0,
                is_inheritance_disabled = True,
                has_inheritance_disabled_categories_or_articles = True,
                country_flag_code = '',
                display_name = '',
                is_home_page_enabled = True,
                version_display_name = ''
            )
        else:
            return Language(
        )
        """

    def testLanguage(self):
        """Test Language"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
