# coding: utf-8

"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from d361api.d361api.article_update_workflow_request import ArticleUpdateWorkflowRequest

class TestArticleUpdateWorkflowRequest(unittest.TestCase):
    """ArticleUpdateWorkflowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArticleUpdateWorkflowRequest:
        """Test ArticleUpdateWorkflowRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArticleUpdateWorkflowRequest`
        """
        model = ArticleUpdateWorkflowRequest()
        if include_optional:
            return ArticleUpdateWorkflowRequest(
                project_version_id = '0',
                lang_code = '0',
                user_id = '0',
                article_ids = [
                    ''
                    ],
                workflow_status_info = d361api.models.article_workflow_status.ArticleWorkflowStatus(
                    status_id = '', 
                    due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    comment = '', 
                    assignee_id = '', )
            )
        else:
            return ArticleUpdateWorkflowRequest(
                project_version_id = '0',
                lang_code = '0',
                user_id = '0',
                article_ids = [
                    ''
                    ],
                workflow_status_info = d361api.models.article_workflow_status.ArticleWorkflowStatus(
                    status_id = '', 
                    due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    comment = '', 
                    assignee_id = '', ),
        )
        """

    def testArticleUpdateWorkflowRequest(self):
        """Test ArticleUpdateWorkflowRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
