# coding: utf-8

"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ArticleStatusCustomer(int, Enum):
    """
    The status of the article: 0 - Draft, 3 - Published
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_3 = 3

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ArticleStatusCustomer from a JSON string"""
        return cls(json.loads(json_str))


