# coding: utf-8

"""
    Document360 Customer API

    Document360 RESTful APIs will allow you to integrate your documentation with your software, allowing you to easily onboard new users, manage your articles and more.   You can find detailed API documentation here : [API Documentation](https://apidocs.document360.io/docs)

    The version of the OpenAPI document: 2.0
    Contact: support@document360.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from d361api.models.bulk_unpublish_category import BulkUnpublishCategory
from typing import Optional, Set
from typing_extensions import Self

class BulkUnpublishCategoryRequest(BaseModel):
    """
    BulkUnpublishCategoryRequest
    """ # noqa: E501
    categories: List[BulkUnpublishCategory] = Field(description="Details of the categories need to be unpublished")
    user_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The ID of the team account that will be marked as the contributor of this unpublish")
    project_version_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The project version ID where the category exists.")
    unpublish_message: Optional[StrictStr] = Field(default=None, description="The unpublish message of the category")
    __properties: ClassVar[List[str]] = ["categories", "user_id", "project_version_id", "unpublish_message"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkUnpublishCategoryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in categories (list)
        _items = []
        if self.categories:
            for _item_categories in self.categories:
                if _item_categories:
                    _items.append(_item_categories.to_dict())
            _dict['categories'] = _items
        # set to None if unpublish_message (nullable) is None
        # and model_fields_set contains the field
        if self.unpublish_message is None and "unpublish_message" in self.model_fields_set:
            _dict['unpublish_message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkUnpublishCategoryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "categories": [BulkUnpublishCategory.from_dict(_item) for _item in obj["categories"]] if obj.get("categories") is not None else None,
            "user_id": obj.get("user_id"),
            "project_version_id": obj.get("project_version_id"),
            "unpublish_message": obj.get("unpublish_message")
        })
        return _obj


